import AppKit
import Carbon.HIToolbox

/// A temporary clipboard owner. A data request is evidence of a read, not proof
/// that a particular editor inserted the text. Inspired by Handy's MIT-licensed
/// macOS paste transaction; see Resources/Licenses/PasteReferences.txt.
final class ClipboardPaste: NSObject, NSPasteboardItemDataProvider {
    private let board: NSPasteboard
    private let text: String
    private let original: [[(NSPasteboard.PasteboardType, Data)]]
    private let now: () -> TimeInterval
    private let marker = Data(UUID().uuidString.utf8)
    private static let transactionType = NSPasteboard.PasteboardType("com.phil.dji-mic-remote.paste-transaction")
    private var changeCount = -1
    private(set) var readAt: TimeInterval?
    private var finished = false
    var ownsClipboard: Bool {
        !finished && board.changeCount == changeCount
            && board.data(forType: Self.transactionType) == marker && board.changeCount == changeCount
    }

    init?(text: String, board: NSPasteboard = .general, now: @escaping () -> TimeInterval = { ProcessInfo.processInfo.systemUptime }) {
        self.board = board; self.text = text; self.now = now
        let initialCount = board.changeCount
        var snapshot: [[(NSPasteboard.PasteboardType, Data)]] = []
        for item in board.pasteboardItems ?? [] {
            var representations: [(NSPasteboard.PasteboardType, Data)] = []
            for type in item.types {
                // Do not silently discard a promised image/file/custom format
                // that could not be materialized, or replace a newer user copy.
                guard let data = item.data(forType: type) else { return nil }
                representations.append((type, data))
            }
            snapshot.append(representations)
        }
        guard board.changeCount == initialCount else { return nil }
        original = snapshot
        super.init()
        let item = NSPasteboardItem()
        item.setDataProvider(self, forTypes: [.string])
        item.setData(marker, forType: Self.transactionType)
        for marker in ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"] {
            item.setData(Data(), forType: .init(marker))
        }
        let clearedCount = board.clearContents()
        guard board.writeObjects([item]) else {
            if board.changeCount == clearedCount { restore() }
            return nil
        }
        changeCount = board.changeCount
        guard ownsClipboard else { return nil }
    }
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        guard type == .string else { return }
        readAt = now(); item.setString(text, forType: .string)
    }
    func finish() {
        guard !finished else { return }
        let restoreOriginal = ownsClipboard
        finished = true
        if restoreOriginal { restore() }
    }
    private func restore() {
        board.clearContents()
        let items = original.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { board.writeObjects(items) }
    }
}

/// The same session-level Command–V event pair used by Maccy/Clipy. Unlike
/// Flow's held shortcut, paste needs no separately injected modifier key.
struct PasteKeystroke {
    /// Session flags include our synthetic Command–V, even after V is released.
    /// Only hardware state answers whether the user is holding a modifier.
    static func physicalModifiers(read: (CGEventSourceStateID) -> CGEventFlags = CGEventSource.flagsState) -> CGEventFlags {
        read(.hidSystemState)
    }
    var keyCode: () -> CGKeyCode? = PasteKeystroke.pasteKeyCode
    var makeEvent: (CGKeyCode, Bool) -> CGEvent? = {
        CGEvent(keyboardEventSource: CGEventSource(stateID: .combinedSessionState), virtualKey: $0, keyDown: $1)
    }
    var post: (CGEvent) -> Void = { $0.post(tap: .cgSessionEventTap) }
    var pause: () async throws -> Void = { try await Task.sleep(nanoseconds: 8_000_000) }
    @MainActor func send() async -> Bool {
        guard !Task.isCancelled, let key = keyCode(),
              let down = makeEvent(key, true), let up = makeEvent(key, false) else { return false }
        // NX_DEVICELCMDKEYMASK: the left-side Command bit used by Maccy.
        let command = CGEventFlags(rawValue: CGEventFlags.maskCommand.rawValue | 0x000008)
        down.flags = command; up.flags = command
        post(down)
        // Let applications process the chord; always balance release even if
        // cancellation arrives during the short event spacing.
        do { try await pause() } catch { post(up); return false }
        post(up)
        return true
    }

    /// Resolve Command-V in the current layout (including Dvorak-QWERTY ⌘).
    /// Adapted from OpenWhispr's MIT-licensed macOS paste helper.
    static func pasteKeyCode() -> CGKeyCode? {
        func layoutData(_ source: TISInputSource?) -> Data? {
            guard let source, let pointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else { return nil }
            return Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
        }
        guard let data = layoutData(TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue())
            ?? layoutData(TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue()) else { return nil }
        return data.withUnsafeBytes { buffer in
            guard let base = buffer.baseAddress else { return nil }
            let layout = base.assumingMemoryBound(to: UCKeyboardLayout.self)
            for key in UInt16(0)..<128 {
                var deadKeyState: UInt32 = 0
                var length = 0
                var characters = [UniChar](repeating: 0, count: 4)
                let result = UCKeyTranslate(layout, key, UInt16(kUCKeyActionDisplay), UInt32(cmdKey) >> 8,
                    UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeyState,
                    characters.count, &length, &characters)
                if result == noErr && String(utf16CodeUnits: characters, count: length) == "v" { return key }
            }
            // A guessed US key can trigger the wrong command on another layout.
            return nil
        }
    }
}
